version: '2'


services:
  composer:
    build:
      context: ./docker/composer
    volumes:
      - ./project_name:/app
      - composer:/composer
    environment:
      GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN}

volumes:
  # global composer volume
  composer:
    driver: local
